export const CAMBIAR_FECHA = 'CAMBIAR_FECHA'
export const SELECCIONAR_REGION = 'SELECCIONAR_REGION'
export const SELECCIONAR_CHILE = 'SELECCIONAR_CHILE'

export const ACTUALIZAR_SERIE = 'ACTUALIZAR_SERIE'
export const RETROCEDER_EN_SERIE = 'RETROCEDER_EN_SERIE'
export const AVANZAR_EN_SERIE = 'AVANZAR_EN_SERIE'
export const FIJAR_POSICION_SERIE = 'FIJAR_POSICION_SERIE'